name: 'CapRover Deploy'
description: 'Action to deploy on Caprover server'
author: 'Alexey Schebelev|YiiMan'
branding:
  icon: upload-cloud
  color: orange
inputs:
  server:
    description: 'CapRover admin panel URL. Ex. https://captain.root.domain.com'
    required: true
  password:
    description: 'CapRover admin password. Use $\{{ secrets.CAPROVER_PASSWORD }} for better security.'
    required: true
  appname:
    description: 'Application name on the CapRover server. Must exists.'
    required: true
  branch:
    description: 'Branch which will be deployed'
    required: false
    default: 'master'
  mode:
    description: 'Mode of execution action, git | docker'
    required: true
    default: 'git'
  image:
    description: 'caprover-action will be use this option as docker image for fastest deploy on caprover server.It should either exist on server, or it has to be public, or on a private repository that CapRover has access to'
    required: false
    default: 'master'

runs:
  using: 'docker'
  image: 'Dockerfile'